//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Cymbol.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class CymbolLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, MUL=14, DIV=15, ADD=16, SUB=17, 
		INT=18, BOOL=19, STRING=20, ID=21, COMMENT=22, ML_COMMENT=23, WS=24;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "MUL", "DIV", "ADD", "SUB", "INT", 
		"BOOL", "STRING", "ID", "COMMENT", "ML_COMMENT", "WS"
	};


	public CymbolLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CymbolLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'='", "'int'", "'bool'", "'string'", "'fun'", "'('", "','", 
		"')'", "'{'", "'}'", "'print'", "'if'", "'*'", "'/'", "'+'", "'-'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "MUL", "DIV", "ADD", "SUB", "INT", "BOOL", "STRING", "ID", 
		"COMMENT", "ML_COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Cymbol.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CymbolLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1A', '\xAB', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x13', '\x6', '\x13', 'h', '\n', '\x13', '\r', 
		'\x13', '\xE', '\x13', 'i', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x5', '\x14', 'u', '\n', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\a', '\x15', 'y', '\n', '\x15', '\f', '\x15', '\xE', '\x15', 
		'|', '\v', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x3', 
		'\x16', '\a', '\x16', '\x82', '\n', '\x16', '\f', '\x16', '\xE', '\x16', 
		'\x85', '\v', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\a', '\x17', '\x8B', '\n', '\x17', '\f', '\x17', '\xE', '\x17', 
		'\x8E', '\v', '\x17', '\x3', '\x17', '\x5', '\x17', '\x91', '\n', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\a', '\x18', '\x9B', '\n', 
		'\x18', '\f', '\x18', '\xE', '\x18', '\x9E', '\v', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', 
		'\x6', '\x19', '\xA6', '\n', '\x19', '\r', '\x19', '\xE', '\x19', '\xA7', 
		'\x3', '\x19', '\x3', '\x19', '\x5', 'z', '\x8C', '\x9C', '\x2', '\x1A', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', 
		'\x19', '\xE', '\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', 
		'#', '\x13', '%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', 
		'\x18', '/', '\x19', '\x31', '\x1A', '\x3', '\x2', '\x6', '\x3', '\x2', 
		'\x32', ';', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', 
		'\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', 
		'\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', '\xB2', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', ')', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x3', '\x33', '\x3', '\x2', 
		'\x2', '\x2', '\x5', '\x35', '\x3', '\x2', '\x2', '\x2', '\a', '\x37', 
		'\x3', '\x2', '\x2', '\x2', '\t', ';', '\x3', '\x2', '\x2', '\x2', '\v', 
		'@', '\x3', '\x2', '\x2', '\x2', '\r', 'G', '\x3', '\x2', '\x2', '\x2', 
		'\xF', 'K', '\x3', '\x2', '\x2', '\x2', '\x11', 'M', '\x3', '\x2', '\x2', 
		'\x2', '\x13', 'O', '\x3', '\x2', '\x2', '\x2', '\x15', 'Q', '\x3', '\x2', 
		'\x2', '\x2', '\x17', 'S', '\x3', '\x2', '\x2', '\x2', '\x19', 'U', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', '[', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'^', '\x3', '\x2', '\x2', '\x2', '\x1F', '`', '\x3', '\x2', '\x2', '\x2', 
		'!', '\x62', '\x3', '\x2', '\x2', '\x2', '#', '\x64', '\x3', '\x2', '\x2', 
		'\x2', '%', 'g', '\x3', '\x2', '\x2', '\x2', '\'', 't', '\x3', '\x2', 
		'\x2', '\x2', ')', 'v', '\x3', '\x2', '\x2', '\x2', '+', '\x7F', '\x3', 
		'\x2', '\x2', '\x2', '-', '\x86', '\x3', '\x2', '\x2', '\x2', '/', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\xA5', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\x34', '\a', '=', '\x2', '\x2', '\x34', '\x4', '\x3', '\x2', 
		'\x2', '\x2', '\x35', '\x36', '\a', '?', '\x2', '\x2', '\x36', '\x6', 
		'\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\a', 'k', '\x2', '\x2', '\x38', 
		'\x39', '\a', 'p', '\x2', '\x2', '\x39', ':', '\a', 'v', '\x2', '\x2', 
		':', '\b', '\x3', '\x2', '\x2', '\x2', ';', '<', '\a', '\x64', '\x2', 
		'\x2', '<', '=', '\a', 'q', '\x2', '\x2', '=', '>', '\a', 'q', '\x2', 
		'\x2', '>', '?', '\a', 'n', '\x2', '\x2', '?', '\n', '\x3', '\x2', '\x2', 
		'\x2', '@', '\x41', '\a', 'u', '\x2', '\x2', '\x41', '\x42', '\a', 'v', 
		'\x2', '\x2', '\x42', '\x43', '\a', 't', '\x2', '\x2', '\x43', '\x44', 
		'\a', 'k', '\x2', '\x2', '\x44', '\x45', '\a', 'p', '\x2', '\x2', '\x45', 
		'\x46', '\a', 'i', '\x2', '\x2', '\x46', '\f', '\x3', '\x2', '\x2', '\x2', 
		'G', 'H', '\a', 'h', '\x2', '\x2', 'H', 'I', '\a', 'w', '\x2', '\x2', 
		'I', 'J', '\a', 'p', '\x2', '\x2', 'J', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'K', 'L', '\a', '*', '\x2', '\x2', 'L', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'M', 'N', '\a', '.', '\x2', '\x2', 'N', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'O', 'P', '\a', '+', '\x2', '\x2', 'P', '\x14', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'R', '\a', '}', '\x2', '\x2', 'R', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'S', 'T', '\a', '\x7F', '\x2', '\x2', 'T', '\x18', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'V', '\a', 'r', '\x2', '\x2', 'V', 'W', '\a', 't', '\x2', 
		'\x2', 'W', 'X', '\a', 'k', '\x2', '\x2', 'X', 'Y', '\a', 'p', '\x2', 
		'\x2', 'Y', 'Z', '\a', 'v', '\x2', '\x2', 'Z', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\a', 'k', '\x2', '\x2', '\\', ']', '\a', 'h', '\x2', 
		'\x2', ']', '\x1C', '\x3', '\x2', '\x2', '\x2', '^', '_', '\a', ',', '\x2', 
		'\x2', '_', '\x1E', '\x3', '\x2', '\x2', '\x2', '`', '\x61', '\a', '\x31', 
		'\x2', '\x2', '\x61', ' ', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', 
		'\a', '-', '\x2', '\x2', '\x63', '\"', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x65', '\a', '/', '\x2', '\x2', '\x65', '$', '\x3', '\x2', '\x2', '\x2', 
		'\x66', 'h', '\t', '\x2', '\x2', '\x2', 'g', '\x66', '\x3', '\x2', '\x2', 
		'\x2', 'h', 'i', '\x3', '\x2', '\x2', '\x2', 'i', 'g', '\x3', '\x2', '\x2', 
		'\x2', 'i', 'j', '\x3', '\x2', '\x2', '\x2', 'j', '&', '\x3', '\x2', '\x2', 
		'\x2', 'k', 'l', '\a', 'v', '\x2', '\x2', 'l', 'm', '\a', 't', '\x2', 
		'\x2', 'm', 'n', '\a', 'w', '\x2', '\x2', 'n', 'u', '\a', 'g', '\x2', 
		'\x2', 'o', 'p', '\a', 'h', '\x2', '\x2', 'p', 'q', '\a', '\x63', '\x2', 
		'\x2', 'q', 'r', '\a', 'n', '\x2', '\x2', 'r', 's', '\a', 'u', '\x2', 
		'\x2', 's', 'u', '\a', 'g', '\x2', '\x2', 't', 'k', '\x3', '\x2', '\x2', 
		'\x2', 't', 'o', '\x3', '\x2', '\x2', '\x2', 'u', '(', '\x3', '\x2', '\x2', 
		'\x2', 'v', 'z', '\a', '$', '\x2', '\x2', 'w', 'y', '\v', '\x2', '\x2', 
		'\x2', 'x', 'w', '\x3', '\x2', '\x2', '\x2', 'y', '|', '\x3', '\x2', '\x2', 
		'\x2', 'z', '{', '\x3', '\x2', '\x2', '\x2', 'z', 'x', '\x3', '\x2', '\x2', 
		'\x2', '{', '}', '\x3', '\x2', '\x2', '\x2', '|', 'z', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\a', '$', '\x2', '\x2', '~', '*', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x83', '\t', '\x3', '\x2', '\x2', '\x80', '\x82', '\t', 
		'\x4', '\x2', '\x2', '\x81', '\x80', '\x3', '\x2', '\x2', '\x2', '\x82', 
		'\x85', '\x3', '\x2', '\x2', '\x2', '\x83', '\x81', '\x3', '\x2', '\x2', 
		'\x2', '\x83', '\x84', '\x3', '\x2', '\x2', '\x2', '\x84', ',', '\x3', 
		'\x2', '\x2', '\x2', '\x85', '\x83', '\x3', '\x2', '\x2', '\x2', '\x86', 
		'\x87', '\a', '\x31', '\x2', '\x2', '\x87', '\x88', '\a', '\x31', '\x2', 
		'\x2', '\x88', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8B', '\v', 
		'\x2', '\x2', '\x2', '\x8A', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8B', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\x3', '\x2', '\x2', 
		'\x2', '\x8C', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x90', '\x3', 
		'\x2', '\x2', '\x2', '\x8E', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8F', 
		'\x91', '\a', '\xF', '\x2', '\x2', '\x90', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\x90', '\x91', '\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x92', '\x93', '\a', '\f', '\x2', '\x2', '\x93', 
		'\x94', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\b', '\x17', '\x2', 
		'\x2', '\x95', '.', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\a', 
		'\x31', '\x2', '\x2', '\x97', '\x98', '\a', ',', '\x2', '\x2', '\x98', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9B', '\v', '\x2', '\x2', 
		'\x2', '\x9A', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x9A', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\a', 
		',', '\x2', '\x2', '\xA0', '\xA1', '\a', '\x31', '\x2', '\x2', '\xA1', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\b', '\x18', '\x2', 
		'\x2', '\xA3', '\x30', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA6', '\t', 
		'\x5', '\x2', '\x2', '\xA5', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x3', 
		'\x2', '\x2', '\x2', '\xA9', '\xAA', '\b', '\x19', '\x2', '\x2', '\xAA', 
		'\x32', '\x3', '\x2', '\x2', '\x2', '\v', '\x2', 'i', 't', 'z', '\x83', 
		'\x8C', '\x90', '\x9C', '\xA7', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
