//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Cymbol.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class CymbolLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, MUL=15, DIV=16, ADD=17, 
		SUB=18, GT=19, GE=20, LT=21, LE=22, EQ=23, NE=24, INT=25, BOOL=26, STRING=27, 
		ID=28, COMMENT=29, ML_COMMENT=30, WS=31;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "MUL", "DIV", "ADD", "SUB", 
		"GT", "GE", "LT", "LE", "EQ", "NE", "INT", "BOOL", "STRING", "ID", "COMMENT", 
		"ML_COMMENT", "WS"
	};


	public CymbolLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CymbolLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'='", "'int'", "'bool'", "'string'", "'fun'", "'('", "','", 
		"')'", "'{'", "'}'", "'print'", "'if'", "'else'", "'*'", "'/'", "'+'", 
		"'-'", "'>'", "'>='", "'<'", "'<='", "'=='", "'!='"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "MUL", "DIV", "ADD", "SUB", "GT", "GE", "LT", "LE", 
		"EQ", "NE", "INT", "BOOL", "STRING", "ID", "COMMENT", "ML_COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Cymbol.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CymbolLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '!', '\xCE', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', 
		'\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', 
		'\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x1A', '\x6', '\x1A', '\x8B', '\n', '\x1A', '\r', 
		'\x1A', '\xE', '\x1A', '\x8C', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1B', '\x5', '\x1B', '\x98', '\n', '\x1B', '\x3', '\x1C', '\x3', 
		'\x1C', '\a', '\x1C', '\x9C', '\n', '\x1C', '\f', '\x1C', '\xE', '\x1C', 
		'\x9F', '\v', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', 
		'\x1D', '\a', '\x1D', '\xA5', '\n', '\x1D', '\f', '\x1D', '\xE', '\x1D', 
		'\xA8', '\v', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\a', '\x1E', '\xAE', '\n', '\x1E', '\f', '\x1E', '\xE', '\x1E', 
		'\xB1', '\v', '\x1E', '\x3', '\x1E', '\x5', '\x1E', '\xB4', '\n', '\x1E', 
		'\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\a', '\x1F', '\xBE', '\n', 
		'\x1F', '\f', '\x1F', '\xE', '\x1F', '\xC1', '\v', '\x1F', '\x3', '\x1F', 
		'\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', 
		'\x6', ' ', '\xC9', '\n', ' ', '\r', ' ', '\xE', ' ', '\xCA', '\x3', ' ', 
		'\x3', ' ', '\x5', '\x9D', '\xAF', '\xBF', '\x2', '!', '\x3', '\x3', '\x5', 
		'\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', 
		'\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', 
		'\x1B', '\xF', '\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', 
		'%', '\x14', '\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', 
		'\x19', '\x31', '\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', 
		'\x39', '\x1E', ';', '\x1F', '=', ' ', '?', '!', '\x3', '\x2', '\x6', 
		'\x3', '\x2', '\x32', ';', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x6', '\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', 
		'\x63', '|', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', '\"', '\x2', 
		'\xD5', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x3', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '\x43', '\x3', '\x2', '\x2', '\x2', '\a', 
		'\x45', '\x3', '\x2', '\x2', '\x2', '\t', 'I', '\x3', '\x2', '\x2', '\x2', 
		'\v', 'N', '\x3', '\x2', '\x2', '\x2', '\r', 'U', '\x3', '\x2', '\x2', 
		'\x2', '\xF', 'Y', '\x3', '\x2', '\x2', '\x2', '\x11', '[', '\x3', '\x2', 
		'\x2', '\x2', '\x13', ']', '\x3', '\x2', '\x2', '\x2', '\x15', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x17', '\x61', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'\x63', '\x3', '\x2', '\x2', '\x2', '\x1B', 'i', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', 'l', '\x3', '\x2', '\x2', '\x2', '\x1F', 'q', '\x3', '\x2', 
		'\x2', '\x2', '!', 's', '\x3', '\x2', '\x2', '\x2', '#', 'u', '\x3', '\x2', 
		'\x2', '\x2', '%', 'w', '\x3', '\x2', '\x2', '\x2', '\'', 'y', '\x3', 
		'\x2', '\x2', '\x2', ')', '{', '\x3', '\x2', '\x2', '\x2', '+', '~', '\x3', 
		'\x2', '\x2', '\x2', '-', '\x80', '\x3', '\x2', '\x2', '\x2', '/', '\x83', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x35', '\x97', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\x99', '\x3', '\x2', '\x2', '\x2', '\x39', '\xA2', 
		'\x3', '\x2', '\x2', '\x2', ';', '\xA9', '\x3', '\x2', '\x2', '\x2', '=', 
		'\xB9', '\x3', '\x2', '\x2', '\x2', '?', '\xC8', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\x42', '\a', '=', '\x2', '\x2', '\x42', '\x4', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\x44', '\a', '?', '\x2', '\x2', '\x44', 
		'\x6', '\x3', '\x2', '\x2', '\x2', '\x45', '\x46', '\a', 'k', '\x2', '\x2', 
		'\x46', 'G', '\a', 'p', '\x2', '\x2', 'G', 'H', '\a', 'v', '\x2', '\x2', 
		'H', '\b', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\a', '\x64', '\x2', 
		'\x2', 'J', 'K', '\a', 'q', '\x2', '\x2', 'K', 'L', '\a', 'q', '\x2', 
		'\x2', 'L', 'M', '\a', 'n', '\x2', '\x2', 'M', '\n', '\x3', '\x2', '\x2', 
		'\x2', 'N', 'O', '\a', 'u', '\x2', '\x2', 'O', 'P', '\a', 'v', '\x2', 
		'\x2', 'P', 'Q', '\a', 't', '\x2', '\x2', 'Q', 'R', '\a', 'k', '\x2', 
		'\x2', 'R', 'S', '\a', 'p', '\x2', '\x2', 'S', 'T', '\a', 'i', '\x2', 
		'\x2', 'T', '\f', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', 'h', '\x2', 
		'\x2', 'V', 'W', '\a', 'w', '\x2', '\x2', 'W', 'X', '\a', 'p', '\x2', 
		'\x2', 'X', '\xE', '\x3', '\x2', '\x2', '\x2', 'Y', 'Z', '\a', '*', '\x2', 
		'\x2', 'Z', '\x10', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\a', '.', 
		'\x2', '\x2', '\\', '\x12', '\x3', '\x2', '\x2', '\x2', ']', '^', '\a', 
		'+', '\x2', '\x2', '^', '\x14', '\x3', '\x2', '\x2', '\x2', '_', '`', 
		'\a', '}', '\x2', '\x2', '`', '\x16', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'\x62', '\a', '\x7F', '\x2', '\x2', '\x62', '\x18', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\a', 'r', '\x2', '\x2', '\x64', '\x65', '\a', 
		't', '\x2', '\x2', '\x65', '\x66', '\a', 'k', '\x2', '\x2', '\x66', 'g', 
		'\a', 'p', '\x2', '\x2', 'g', 'h', '\a', 'v', '\x2', '\x2', 'h', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', 'k', '\x2', '\x2', 'j', 'k', 
		'\a', 'h', '\x2', '\x2', 'k', '\x1C', '\x3', '\x2', '\x2', '\x2', 'l', 
		'm', '\a', 'g', '\x2', '\x2', 'm', 'n', '\a', 'n', '\x2', '\x2', 'n', 
		'o', '\a', 'u', '\x2', '\x2', 'o', 'p', '\a', 'g', '\x2', '\x2', 'p', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\a', ',', '\x2', '\x2', 
		'r', ' ', '\x3', '\x2', '\x2', '\x2', 's', 't', '\a', '\x31', '\x2', '\x2', 
		't', '\"', '\x3', '\x2', '\x2', '\x2', 'u', 'v', '\a', '-', '\x2', '\x2', 
		'v', '$', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', '/', '\x2', '\x2', 
		'x', '&', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', '@', '\x2', '\x2', 
		'z', '(', '\x3', '\x2', '\x2', '\x2', '{', '|', '\a', '@', '\x2', '\x2', 
		'|', '}', '\a', '?', '\x2', '\x2', '}', '*', '\x3', '\x2', '\x2', '\x2', 
		'~', '\x7F', '\a', '>', '\x2', '\x2', '\x7F', ',', '\x3', '\x2', '\x2', 
		'\x2', '\x80', '\x81', '\a', '>', '\x2', '\x2', '\x81', '\x82', '\a', 
		'?', '\x2', '\x2', '\x82', '.', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', 
		'\a', '?', '\x2', '\x2', '\x84', '\x85', '\a', '?', '\x2', '\x2', '\x85', 
		'\x30', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\a', '#', '\x2', 
		'\x2', '\x87', '\x88', '\a', '?', '\x2', '\x2', '\x88', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\x89', '\x8B', '\t', '\x2', '\x2', '\x2', '\x8A', 
		'\x89', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\x3', '\x2', '\x2', 
		'\x2', '\x8C', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x34', '\x3', '\x2', '\x2', '\x2', '\x8E', 
		'\x8F', '\a', 'v', '\x2', '\x2', '\x8F', '\x90', '\a', 't', '\x2', '\x2', 
		'\x90', '\x91', '\a', 'w', '\x2', '\x2', '\x91', '\x98', '\a', 'g', '\x2', 
		'\x2', '\x92', '\x93', '\a', 'h', '\x2', '\x2', '\x93', '\x94', '\a', 
		'\x63', '\x2', '\x2', '\x94', '\x95', '\a', 'n', '\x2', '\x2', '\x95', 
		'\x96', '\a', 'u', '\x2', '\x2', '\x96', '\x98', '\a', 'g', '\x2', '\x2', 
		'\x97', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x97', '\x92', '\x3', '\x2', 
		'\x2', '\x2', '\x98', '\x36', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9D', 
		'\a', '$', '\x2', '\x2', '\x9A', '\x9C', '\v', '\x2', '\x2', '\x2', '\x9B', 
		'\x9A', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9F', '\x3', '\x2', '\x2', 
		'\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x9D', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9E', '\xA0', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\x9D', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\a', '$', '\x2', 
		'\x2', '\xA1', '\x38', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA6', '\t', 
		'\x3', '\x2', '\x2', '\xA3', '\xA5', '\t', '\x4', '\x2', '\x2', '\xA4', 
		'\xA3', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA8', '\x3', '\x2', '\x2', 
		'\x2', '\xA6', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\x3', 
		'\x2', '\x2', '\x2', '\xA7', ':', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xAA', '\a', '\x31', '\x2', 
		'\x2', '\xAA', '\xAB', '\a', '\x31', '\x2', '\x2', '\xAB', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '\xAC', '\xAE', '\v', '\x2', '\x2', '\x2', '\xAD', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xAF', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xAD', '\x3', 
		'\x2', '\x2', '\x2', '\xB0', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB1', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB4', '\a', '\xF', '\x2', 
		'\x2', '\xB3', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB4', '\x3', 
		'\x2', '\x2', '\x2', '\xB4', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB5', 
		'\xB6', '\a', '\f', '\x2', '\x2', '\xB6', '\xB7', '\x3', '\x2', '\x2', 
		'\x2', '\xB7', '\xB8', '\b', '\x1E', '\x2', '\x2', '\xB8', '<', '\x3', 
		'\x2', '\x2', '\x2', '\xB9', '\xBA', '\a', '\x31', '\x2', '\x2', '\xBA', 
		'\xBB', '\a', ',', '\x2', '\x2', '\xBB', '\xBF', '\x3', '\x2', '\x2', 
		'\x2', '\xBC', '\xBE', '\v', '\x2', '\x2', '\x2', '\xBD', '\xBC', '\x3', 
		'\x2', '\x2', '\x2', '\xBE', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xBF', 
		'\xC0', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xBD', '\x3', '\x2', '\x2', 
		'\x2', '\xC0', '\xC2', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xBF', '\x3', 
		'\x2', '\x2', '\x2', '\xC2', '\xC3', '\a', ',', '\x2', '\x2', '\xC3', 
		'\xC4', '\a', '\x31', '\x2', '\x2', '\xC4', '\xC5', '\x3', '\x2', '\x2', 
		'\x2', '\xC5', '\xC6', '\b', '\x1F', '\x2', '\x2', '\xC6', '>', '\x3', 
		'\x2', '\x2', '\x2', '\xC7', '\xC9', '\t', '\x5', '\x2', '\x2', '\xC8', 
		'\xC7', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCA', '\x3', '\x2', '\x2', 
		'\x2', '\xCA', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x3', 
		'\x2', '\x2', '\x2', '\xCB', '\xCC', '\x3', '\x2', '\x2', '\x2', '\xCC', 
		'\xCD', '\b', ' ', '\x2', '\x2', '\xCD', '@', '\x3', '\x2', '\x2', '\x2', 
		'\v', '\x2', '\x8C', '\x97', '\x9D', '\xA6', '\xAF', '\xB3', '\xBF', '\xCA', 
		'\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
