//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Cymbol.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class CymbolLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, MUL=15, DIV=16, ADD=17, 
		SUB=18, INT=19, BOOL=20, STRING=21, ID=22, COMMENT=23, ML_COMMENT=24, 
		WS=25;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "MUL", "DIV", "ADD", "SUB", 
		"INT", "BOOL", "STRING", "ID", "COMMENT", "ML_COMMENT", "WS"
	};


	public CymbolLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public CymbolLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "';'", "'='", "'int'", "'bool'", "'string'", "'fun'", "'('", "','", 
		"')'", "'{'", "'}'", "'print'", "'if'", "'else'", "'*'", "'/'", "'+'", 
		"'-'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "MUL", "DIV", "ADD", "SUB", "INT", "BOOL", "STRING", 
		"ID", "COMMENT", "ML_COMMENT", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Cymbol.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static CymbolLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1B', '\xB2', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x6', 
		'\x14', 'o', '\n', '\x14', '\r', '\x14', '\xE', '\x14', 'p', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x5', '\x15', '|', '\n', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\a', '\x16', '\x80', '\n', '\x16', 
		'\f', '\x16', '\xE', '\x16', '\x83', '\v', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x17', '\x3', '\x17', '\a', '\x17', '\x89', '\n', '\x17', 
		'\f', '\x17', '\xE', '\x17', '\x8C', '\v', '\x17', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\a', '\x18', '\x92', '\n', '\x18', 
		'\f', '\x18', '\xE', '\x18', '\x95', '\v', '\x18', '\x3', '\x18', '\x5', 
		'\x18', '\x98', '\n', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\a', '\x19', '\xA2', '\n', '\x19', '\f', '\x19', '\xE', '\x19', '\xA5', 
		'\v', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x1A', '\x6', '\x1A', '\xAD', '\n', '\x1A', '\r', 
		'\x1A', '\xE', '\x1A', '\xAE', '\x3', '\x1A', '\x3', '\x1A', '\x5', '\x81', 
		'\x93', '\xA3', '\x2', '\x1B', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', 
		')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', '\x1A', '\x33', 
		'\x1B', '\x3', '\x2', '\x6', '\x3', '\x2', '\x32', ';', '\x5', '\x2', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', '\x2', '\x32', ';', 
		'\x43', '\\', '\x61', '\x61', '\x63', '|', '\x5', '\x2', '\v', '\f', '\xF', 
		'\xF', '\"', '\"', '\x2', '\xB9', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x3', '\x35', '\x3', '\x2', 
		'\x2', '\x2', '\x5', '\x37', '\x3', '\x2', '\x2', '\x2', '\a', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\t', '=', '\x3', '\x2', '\x2', '\x2', '\v', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\r', 'I', '\x3', '\x2', '\x2', '\x2', 
		'\xF', 'M', '\x3', '\x2', '\x2', '\x2', '\x11', 'O', '\x3', '\x2', '\x2', 
		'\x2', '\x13', 'Q', '\x3', '\x2', '\x2', '\x2', '\x15', 'S', '\x3', '\x2', 
		'\x2', '\x2', '\x17', 'U', '\x3', '\x2', '\x2', '\x2', '\x19', 'W', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', ']', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'`', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x65', '\x3', '\x2', '\x2', 
		'\x2', '!', 'g', '\x3', '\x2', '\x2', '\x2', '#', 'i', '\x3', '\x2', '\x2', 
		'\x2', '%', 'k', '\x3', '\x2', '\x2', '\x2', '\'', 'n', '\x3', '\x2', 
		'\x2', '\x2', ')', '{', '\x3', '\x2', '\x2', '\x2', '+', '}', '\x3', '\x2', 
		'\x2', '\x2', '-', '\x86', '\x3', '\x2', '\x2', '\x2', '/', '\x8D', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\xAC', '\x3', '\x2', '\x2', '\x2', '\x35', '\x36', '\a', '=', '\x2', 
		'\x2', '\x36', '\x4', '\x3', '\x2', '\x2', '\x2', '\x37', '\x38', '\a', 
		'?', '\x2', '\x2', '\x38', '\x6', '\x3', '\x2', '\x2', '\x2', '\x39', 
		':', '\a', 'k', '\x2', '\x2', ':', ';', '\a', 'p', '\x2', '\x2', ';', 
		'<', '\a', 'v', '\x2', '\x2', '<', '\b', '\x3', '\x2', '\x2', '\x2', '=', 
		'>', '\a', '\x64', '\x2', '\x2', '>', '?', '\a', 'q', '\x2', '\x2', '?', 
		'@', '\a', 'q', '\x2', '\x2', '@', '\x41', '\a', 'n', '\x2', '\x2', '\x41', 
		'\n', '\x3', '\x2', '\x2', '\x2', '\x42', '\x43', '\a', 'u', '\x2', '\x2', 
		'\x43', '\x44', '\a', 'v', '\x2', '\x2', '\x44', '\x45', '\a', 't', '\x2', 
		'\x2', '\x45', '\x46', '\a', 'k', '\x2', '\x2', '\x46', 'G', '\a', 'p', 
		'\x2', '\x2', 'G', 'H', '\a', 'i', '\x2', '\x2', 'H', '\f', '\x3', '\x2', 
		'\x2', '\x2', 'I', 'J', '\a', 'h', '\x2', '\x2', 'J', 'K', '\a', 'w', 
		'\x2', '\x2', 'K', 'L', '\a', 'p', '\x2', '\x2', 'L', '\xE', '\x3', '\x2', 
		'\x2', '\x2', 'M', 'N', '\a', '*', '\x2', '\x2', 'N', '\x10', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'P', '\a', '.', '\x2', '\x2', 'P', '\x12', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'R', '\a', '+', '\x2', '\x2', 'R', '\x14', '\x3', '\x2', 
		'\x2', '\x2', 'S', 'T', '\a', '}', '\x2', '\x2', 'T', '\x16', '\x3', '\x2', 
		'\x2', '\x2', 'U', 'V', '\a', '\x7F', '\x2', '\x2', 'V', '\x18', '\x3', 
		'\x2', '\x2', '\x2', 'W', 'X', '\a', 'r', '\x2', '\x2', 'X', 'Y', '\a', 
		't', '\x2', '\x2', 'Y', 'Z', '\a', 'k', '\x2', '\x2', 'Z', '[', '\a', 
		'p', '\x2', '\x2', '[', '\\', '\a', 'v', '\x2', '\x2', '\\', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', ']', '^', '\a', 'k', '\x2', '\x2', '^', '_', '\a', 
		'h', '\x2', '\x2', '_', '\x1C', '\x3', '\x2', '\x2', '\x2', '`', '\x61', 
		'\a', 'g', '\x2', '\x2', '\x61', '\x62', '\a', 'n', '\x2', '\x2', '\x62', 
		'\x63', '\a', 'u', '\x2', '\x2', '\x63', '\x64', '\a', 'g', '\x2', '\x2', 
		'\x64', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', ',', 
		'\x2', '\x2', '\x66', ' ', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', 
		'\x31', '\x2', '\x2', 'h', '\"', '\x3', '\x2', '\x2', '\x2', 'i', 'j', 
		'\a', '-', '\x2', '\x2', 'j', '$', '\x3', '\x2', '\x2', '\x2', 'k', 'l', 
		'\a', '/', '\x2', '\x2', 'l', '&', '\x3', '\x2', '\x2', '\x2', 'm', 'o', 
		'\t', '\x2', '\x2', '\x2', 'n', 'm', '\x3', '\x2', '\x2', '\x2', 'o', 
		'p', '\x3', '\x2', '\x2', '\x2', 'p', 'n', '\x3', '\x2', '\x2', '\x2', 
		'p', 'q', '\x3', '\x2', '\x2', '\x2', 'q', '(', '\x3', '\x2', '\x2', '\x2', 
		'r', 's', '\a', 'v', '\x2', '\x2', 's', 't', '\a', 't', '\x2', '\x2', 
		't', 'u', '\a', 'w', '\x2', '\x2', 'u', '|', '\a', 'g', '\x2', '\x2', 
		'v', 'w', '\a', 'h', '\x2', '\x2', 'w', 'x', '\a', '\x63', '\x2', '\x2', 
		'x', 'y', '\a', 'n', '\x2', '\x2', 'y', 'z', '\a', 'u', '\x2', '\x2', 
		'z', '|', '\a', 'g', '\x2', '\x2', '{', 'r', '\x3', '\x2', '\x2', '\x2', 
		'{', 'v', '\x3', '\x2', '\x2', '\x2', '|', '*', '\x3', '\x2', '\x2', '\x2', 
		'}', '\x81', '\a', '$', '\x2', '\x2', '~', '\x80', '\v', '\x2', '\x2', 
		'\x2', '\x7F', '~', '\x3', '\x2', '\x2', '\x2', '\x80', '\x83', '\x3', 
		'\x2', '\x2', '\x2', '\x81', '\x82', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x7F', '\x3', '\x2', '\x2', '\x2', '\x82', '\x84', '\x3', '\x2', '\x2', 
		'\x2', '\x83', '\x81', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', 
		'$', '\x2', '\x2', '\x85', ',', '\x3', '\x2', '\x2', '\x2', '\x86', '\x8A', 
		'\t', '\x3', '\x2', '\x2', '\x87', '\x89', '\t', '\x4', '\x2', '\x2', 
		'\x88', '\x87', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8C', '\x3', '\x2', 
		'\x2', '\x2', '\x8A', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', 
		'\x3', '\x2', '\x2', '\x2', '\x8B', '.', '\x3', '\x2', '\x2', '\x2', '\x8C', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\a', '\x31', '\x2', 
		'\x2', '\x8E', '\x8F', '\a', '\x31', '\x2', '\x2', '\x8F', '\x93', '\x3', 
		'\x2', '\x2', '\x2', '\x90', '\x92', '\v', '\x2', '\x2', '\x2', '\x91', 
		'\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x93', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x94', '\x97', '\x3', '\x2', '\x2', '\x2', '\x95', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x96', '\x98', '\a', '\xF', '\x2', 
		'\x2', '\x97', '\x96', '\x3', '\x2', '\x2', '\x2', '\x97', '\x98', '\x3', 
		'\x2', '\x2', '\x2', '\x98', '\x99', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x9A', '\a', '\f', '\x2', '\x2', '\x9A', '\x9B', '\x3', '\x2', '\x2', 
		'\x2', '\x9B', '\x9C', '\b', '\x18', '\x2', '\x2', '\x9C', '\x30', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\x9E', '\a', '\x31', '\x2', '\x2', '\x9E', 
		'\x9F', '\a', ',', '\x2', '\x2', '\x9F', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xA0', '\xA2', '\v', '\x2', '\x2', '\x2', '\xA1', '\xA0', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA3', 
		'\xA4', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', 
		'\x2', '\xA4', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA3', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\xA7', '\a', ',', '\x2', '\x2', '\xA7', 
		'\xA8', '\a', '\x31', '\x2', '\x2', '\xA8', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xA9', '\xAA', '\b', '\x19', '\x2', '\x2', '\xAA', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xAD', '\t', '\x5', '\x2', '\x2', '\xAC', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\x3', '\x2', '\x2', 
		'\x2', '\xAE', '\xAC', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xAF', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB0', 
		'\xB1', '\b', '\x1A', '\x2', '\x2', '\xB1', '\x34', '\x3', '\x2', '\x2', 
		'\x2', '\v', '\x2', 'p', '{', '\x81', '\x8A', '\x93', '\x97', '\xA3', 
		'\xAE', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
